steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      ".",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/docker-registry/daos-centos",
    ]

images:
- "us-central1-docker.pkg.dev/$PROJECT_ID/docker-registry/daos-centos"
tags: ["daos"]