steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "https://github.com/daos-stack/daos.git#lei/DAOS-12142",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/docker-registry/daos-el8-ld-preload-pil4dfs",
        "-f",
        "utils/docker/Dockerfile.el.8",
        "--build-arg",
        "JOBS=32",
        "--build-arg",
        "DEPS_JOBS=32",
      ]

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/docker-registry/daos-el8-ld-preload-pil4dfs"
tags: ["daos"]
